console.log('hello world');
console.log('halo dunia');
console.log('ciao mondo');
console.log('hola mundo');
console.log('ola mundo');
console.log('ahlan aleaalamia');
console.log('hallo welt');
console.log('namaste shabdkosh');
console.log(' habari dunia');
console.log('vanakkam ulakam');